#ifndef ___Balls__GUIControl__H___
#define ___Balls__GUIControl__H___

enum BallsGUIControl
{

	BGC_BOMBNORMAL = 10,
	BGC_BOMBHOVER,
	BGC_BOMBPRESSED,
	BGC_BOMBPRESSEDHOVER,
	BGC_SENDNORMAL,
	BGC_SENDHOVER,
	BGC_CANCELNORMAL,
	BGC_CANCELHOVER,
	BGC_MESSAGEBOX,
	BGC_FORWARDNORMAL,
	BGC_FORWARDHOVER,
	BGC_FORWARDPRESSED,
	BGC_BACKNORMAL,
	BGC_BACKHOVER,
	BGC_TROPHYNORMAL,
	BGC_TROPHYHOVER
};

#endif
